name: Generate GitHub Commit Heatmap

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정(UTC)마다 실행
  workflow_dispatch: # 수동 실행 가능

jobs:
  generate-heatmap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "Your GitHub Username"
        git config --global user.email "your-email@example.com"

    - name: Clone refactoring-kata repository
      run: |
        git clone https://github.com/suojae/refactoring-kata.git refactoring-kata
        cd refactoring-kata
        git log --pretty=format:"%ad %H" --date=short > ../commit_dates.txt

    - name: Generate commit heatmap
      run: |
        mkdir heatmap-repo
        cd heatmap-repo
        git init
        # 가져온 commit_dates.txt 파일의 날짜를 기반으로 커밋 생성
        while read -r date hash; do
          GIT_COMMITTER_DATE="$date" GIT_AUTHOR_DATE="$date" git commit --allow-empty -m "Commit on $date"
        done < ../commit_dates.txt

    - name: Push to sujae repository
      run: |
        git remote add origin https://github.com/suojae/suojae.git
        git branch -M main
        git push -u origin main --force
